# Generated by Django 4.1 on 2022-10-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(max_length=100)),
                ('nombre_etoiles', models.PositiveIntegerField(blank=True, null=True)),
                ('services_equipements', models.CharField(blank=True, choices=[('Piscine', 'Piscine'), ('SPA', 'SPA'), ('Salle de fitness', 'Salle de fitness'), ('Air Conditionné', 'Air Conditionné'), ('Restaurant', 'Restaurant'), ('Parking', 'Parking'), ('Animaux accepté', 'Animaux accepté'), ('Navette Aéroport', 'Navette Aéroport'), ("Centre d'affaires", "Centre d'affaires"), ('Facilités pour handicapés ', 'Facilités pour handicapés '), ('Wifi', 'Wifi'), ('Salles de réunions', 'Salles de réunions'), ('Tennis', 'Tennis'), ('Golf', 'Golf'), ('Cuisine', 'Cuisine'), ("Garde d'animaux", "Garde d'animaux"), ('Plage', 'Plage'), ('Casino', 'Casino'), ('Jacuzzi', 'Jacuzzi'), ('Sauna', 'Sauna'), ('Solarium', 'Solarium'), ('Massage', 'Massage'), ('Voiturier', 'Voiturier'), ('Mini Bar', 'Mini Bar'), ('Télévision', 'Télévision'), ('Service de chambre', 'Service de chambre'), ('Parking surveillé', 'Parking surveillé')], max_length=100)),
            ],
        ),
    ]
