# Generated by Django 4.1 on 2022-11-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='nombre_etoiles',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=1, max_length=150),
        ),
        migrations.AddField(
            model_name='hotels',
            name='services_equipements',
            field=models.CharField(choices=[('SWIMMING_POOL', 'Piscine'), ('SPA', 'SPA'), ('RESTAURANT', 'Restaurant'), ('PETS_ALLOWED', 'Animaux autorisés'), ('BEACH', 'Plage'), ('FITNESS_CENTER', 'Salle de sport'), ('AIRPORT_SHUTTLE', 'navette aéroport'), (' MASSAGE', 'Massage'), ('BAR or LOUNGE', 'Bar'), ('ROOM_SERVICE', 'Room Service')], default='SWIMMING_POOL', max_length=150),
        ),
    ]
