# Generated by Django 4.1 on 2022-10-28 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_hotels_nombre_etoiles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotels',
            old_name='nombre_etoiles',
            new_name='nombre_étoiles',
        ),
        migrations.RenameField(
            model_name='hotels',
            old_name='services_equipements',
            new_name='services_et_équipements',
        ),
    ]
