# Generated by Django 4.1 on 2022-10-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_apipreferencemodel_pays_de_depart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apipreferencemodel',
            name='pays_de_depart',
            field=models.CharField(max_length=3),
        ),
    ]
