# Generated by Django 4.1 on 2022-10-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vol', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vols',
            name='classe_vol',
        ),
        migrations.AddField(
            model_name='vols',
            name='infant',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vols',
            name='nombre_adult',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vols',
            name='nombre_enfant',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
