# Generated by Django 4.1 on 2022-10-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vol', '0002_remove_vols_classe_vol_vols_infant_vols_nombre_adult_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vols',
            name='infant',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vols',
            name='nombre_adult',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vols',
            name='nombre_enfant',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
