# Generated by Django 4.1 on 2022-11-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vol', '0004_alter_vols_infant_alter_vols_nombre_adult_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vols',
            name='infant',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='vols',
            name='nombre_adult',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='vols',
            name='nombre_enfant',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
